version: "3"
services:
  frontend:
    restart: always
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    networks:
      - confessional-app
  backend:
    restart: always
    build:
      context: ./backend
    image: backend
    ports:
      - "3001:3001"
    networks:
      - confessional-app
  mongo:
    restart: always
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    networks:
      - confessional-app
    volumes:
      - mongo-data:/data/db
networks:
  confessional-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
